export const cfg = {
  port: parseInt(process.env.GATEWAY_PORT || "8787", 10),
  tenantHeader: process.env.TENANT_HEADER || "X-Tenant-Id",
  hmacHeader: process.env.HMAC_HEADER || "X-Signature",
  hmacSecret: process.env.HMAC_SECRET || "dev_shared_secret",
  chatUrl: "http://chat:3001",
  jwtPublicKey: process.env.JWT_PUBLIC_KEY || "",
  adminToken: process.env.ADMIN_API_TOKEN || "",
  corsOrigins: process.env.CORS_ORIGINS || "",
  qdrantUrl: process.env.QDRANT_URL || "http://qdrant:6333",
  qdrantApiKey: process.env.QDRANT_API_KEY || "",
  ollamaUrl: process.env.OLLAMA_BASE_URL || "http://ollama:11434",
  embedModel: process.env.EMBED_MODEL || "nomic-embed-text",
  geminiKey: process.env.GOOGLE_API_KEY || "",
  geminiEmbedModel: process.env.GEMINI_EMBED_MODEL || "text-embedding-004",
  ingestCron: process.env.INGEST_CRON || "",
  chatProviderMode: (process.env.MODEL || "local").toLowerCase() === "cloud" ? "cloud" : "local",
  defaultEmbedProvider: (process.env.EMBED_PROVIDER || "local").toLowerCase() === "cloud" ? "gemini" : "ollama",
  defaultInternalCrawlDepth: parseInt(process.env.CRAWL_INTERNAL_DEPTH || "0", 10),
  defaultExternalCrawlDepth: parseInt(process.env.CRAWL_EXTERNAL_DEPTH || "0", 10),
};
